--- 
apiVersion: v1
kind: Service

metadata: 
  name: fleetman-webapp  

spec: 
  
  ports: 
    - name: http
      nodePort: 30080
      port: 80
  
  selector: 
    app: webapp
      
  type: NodePort

--- 
apiVersion: v1
kind: Service

metadata: 
  name: fleetman-queue  

spec: 
  
  ports: 
    - name: http
      nodePort: 30010
      port: 8161

    - name: endpoint
      port: 61616
  
  selector: 
    app: queue
  
  type: NodePort

--- 
apiVersion: v1
kind: Service

metadata: 
  name: fleetman-position-tracker  

spec: 
  
  ports: 
    - name: http
      port: 8080
  
  selector: 
    app: position-tracker
  
  type: ClusterIP

--- 
apiVersion: v1
kind: Service

metadata: 
  name: fleetman-api-gateway  

spec: 
  
  ports: 
    - name: http
      port: 8080
      nodePort: 30020
  
  selector: 
    app: api-gateway
  
  type: NodePort    
